### ISSUE TITLE
Upgrade 2: Store Credit Off Ramp

### ISSUE THREAD

**Issue by dylviz** [avendure/VendurePlugin-Store-Credit#6]
Since store-credit enters the platform by a customer claiming the credit (or purchasing a NPP), then each seller that holds store-credit means they must have sold something.

- [ ] At this point, the seller may want to exchange their credit for fiat currency (off-ramp). To do this, the seller should submit a form to "Request Credit Exchange" through the admin frontend.

- [ ] Once this form is submitted the seller's information will be sent to a Queue for the Superadmin to manually process.

- [ ] The amount requested should be placed "On-hold" until the Superadmin can process the request. This means that if a Seller has a balance of 100 credits then submits a request to exchange 10 then the available balance of the seller should be 90.
- [ ] There should also be an Exchange Fee set by the Superadmin. This means that if the Seller requests to exchange 10 credits and the Exchange Fee is set to 10% then the Seller will receive 9 credits worth of Fiat. The other 1 credit will be deleted or sent to Superadmin's account

- [ ] The Superadmin should also have the option to set a minimum exchange requirement. This means that the Seller would not be able to submit an exchange request unless (Requested exchange quantity >= Minimum exchange requirement) 

- [ ]  The Seller can cancel their request submitted to the superadmin at which point, their available balance will return to 100 credits and the request will be removed from the Superadmin's Queue. 

- [ ] The superadmin will accept/deny the request.

- [ ] If the superadmin denies the request, the Seller's balance will also return 100 credits

- [ ] If the Superadmin accepts the request, it will create an order with non-physical product (store-credit) and the quantity will be set to the number that is received from the "Request Credit Exchange" form submission and will use the plugin's set exchange rate for the currency.

- [ ] The superadmin will process the payment through a 3rd party provider (Stripe, etc) and the money will be sent to the Seller's account.

**Comment by BijanRegmi** [comment]
In the last checkpoint, how exactly will the money be sent to the Seller's account? Is the order being created in seller's channel with seller's payment method?

**Comment by dylviz** [comment]
> In the last checkpoint, how exactly will the money be sent to the Seller's account? Is the order being created in seller's channel with seller's payment method?

Yes, exactly

**Comment by BijanRegmi** [comment]
And who will be the customer for assigned to that order? Creating order requires alot of steps like setting billing address, shipping method and all; which might be a bit tedious.

**Comment by dylviz** [comment]
I see. Is it possible to assign the Superadmin as the customer to the order?

The superadmin will be logged in when the Request is Accepted.

**Comment by dylviz** [comment]
The only other option I can think of is that the Superadmin has to link to a customer account in the global settings. Then I can create an additional customer account and have a relation with the superadmin

**Comment by dylviz** [comment]
Maybe not in the global setting but somewhere that has an option to "Link a customer account". If we can link it by email that would be great

**Comment by BijanRegmi** [comment]
And what will be the default behavior if there is no customer with the same email as superadmin? Also note that the default email for superadmin is simply "superadmin", this might break email verification in some of the payment services.

I guess a better option would be for the superadmin to externally pay the seller via the payment options provided by the seller while requesting credit exchange; and then upload a invoice link for proof.

**Comment by dylviz** [comment]
> And what will be the default behavior if there is no customer with the same email as superadmin? Also note that the default email for superadmin is simply "superadmin", this might break email verification in some of the payment services.

I don't mean link them with "superadmin" email but rather in the adminUI, allow the superadmin to input a customer email address in the settings.

Then we could lookup the customer account by that email and save it as a linked account.

By default, if there's no linked account then the superadmin should not have the ability to "Accept" any exchange requests but can still deny.

For example, i would create a customer accout with email "admin@mycompany.com" then i would login to the superadmin account and go into settings under "Link a customer account" then input the same email I used. 

I could receive a green pop up notification saying the "account was successfully linked" if we do a lookup and find the customer account matching that email. So we won't use "superadmin" as the email lookup

**Comment by BijanRegmi** [comment]
Maybe we can replace the user relation in seller entity with customer. And use this as the customer that belongs to that seller. This way when a superadmin accepts the credit exchange we can use the customer linked to the `Default Seller` of the superadmin channel.

**Comment by dylviz** [comment]
It sounds like it would be a good idea to replace the user relation but wouldn't that require other changes to the code? I forget what the user relation was used for but i know we needed for some reason

**Comment by BijanRegmi** [comment]
The user relation is primarily used for linking seller entity to customer. When transferring store credit from seller account to customer account it uses this user relation to find a customer with the same email. If we replace the user relation with customer relation then it will some more direct relation between seller and customer account.
